### ISSUE TITLE
Hide api keys and secrets from version control

### ISSUE THREAD

**Issue by oscarb** [Kladky/align#221]
Hi, 

I read [this article](https://medium.com/ladies-storm-hackathons/how-we-built-our-first-full-stack-javascript-web-app-in-three-weeks-8a4668dbd67c) about your app and found it very interesting :) 

When I looked at your code I found your [configuration for Firebase](https://github.com/align-capstone/align/blob/0d919a09551d8ef9d3557613fbdc1d10e937b7b8/fire/index.js#L5-L10). You should consider generating new keys and avoid secrets in the code that is version controlled. For more information, see 

* [Secrets in the code](https://github.com/blog/1390-secrets-in-the-code)
* [Removing sensitive data from a repository - User Documentation](https://help.github.com/articles/removing-sensitive-data-from-a-repository/)

**Comment by queerviolet** [comment]
Firebase API keys are safe to expose (the older API didn't have keys at all, in fact). Indeed, this config *must* be exposed publicly—Firebase apps typically have no backend, so where would it go if not into frontend code?

See [this stackoverflow answer](https://stackoverflow.com/a/37484053) by Firebase engineer Frank van Puffelen.

@sophiaciocca — I'd close this WAI
